name: Docker Image build and release

on:
  workflow_dispatch:
    inputs:
      major_version:
        description: "Major version (e.g., 1)"
        required: true
      minor_version:
        description: "Minor version (e.g., 0)"
        required: true
      patch_version:
        description: "Patch version (e.g., 0)"
        required: true

jobs:
  build-and-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Combine Versions
      run: |
        echo "FULL_VERSION=${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.${{ github.event.inputs.patch_version }}" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push multi-platform Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/nexus-media/sonarscan-dotnet:${{ env.FULL_VERSION }}
          ghcr.io/nexus-media/sonarscan-dotnet:latest

    - name: Create Release
      id: create_release
      run: |
        gh release create v${{ env.FULL_VERSION }} \
          --repo ${{ github.repository }} \
          --title "Release v${{ env.FULL_VERSION }}" \
          --notes "Release notes for version ${{ env.FULL_VERSION }}" \
          --draft=false \
          --prerelease=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
